project:
  type: website

website:
  title: "ISSS608-Visual Analytics"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Introduction"
        href: "Hands-on_Ex/Introduction/Lesson_Plan.html"
    - text: "In-class Exercise"
    - text: "Take-home exercise"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

